-- This is the main API interface, do not edit this file!
function ExtractSteamId(str)
    str = str:gsub("\\", "/")
    return str:match("([^/]+)$")
end


-- DO NOT EDIT! DO NOT EDIT!
PhysLib = {
    Path = "mods/physlib/script.lua",
    --Path = "mods/3386439236",
    callbackPath = "mods/" .. ExtractSteamId(path) .. "/script.lua",
    Version = 1.3,


    -- concats to "apiFunction(thisScriptPath, additionalArg, additionalArg)"
    callTable = {"API:", "apiFunction", "(thisScriptPath, ", "additionalArg, additionalArg,", ")"},
    
    apiClass = "API:",

    ModName = "Undefined mod name, please parse in PhysLib:Load()",
}
-- #region wrapper





local path = PhysLib.Path
local callTable = PhysLib.callTable 
function PhysLib:Parse(APIFunc, ...)
    callTable[2] = APIFunc
    callTable[4] = table.concat({...}, ", ")
    local scriptCall = table.concat(callTable)
    ExecuteInScript(path, -1, scriptCall)
end


function PhysLib:Call(APIFunc, ...) 
    local scriptCall = self.apiClass .. APIFunc
    local args = {...}
    return CallScript(self.Path, -1, scriptCall, args, nil)
end


function PhysLib:MakeNestedString(str)
    return "'" .. str .. "'"
end

function PhysLib:StringifyTable(t)
    if type(t) == "table" then
        local str = "{"
        for k, v in pairs(t) do
            str = str .. k .. "=" .. self:StringifyTable(v) .. ","
        end
        str = str .. "}"
        return str
    elseif type(t) == "string" then
        return self:MakeNestedString(t)
    else
        return tostring(t)
    end

end

function PhysLib:MakeBackSlashesForwardSlashes(str)
    return string.gsub(str, "\\", "/")
end

function PhysLib:CleanPath(path)
    return string.gsub(path, "\\", "\\\\")
end

function PhysLib:Load(modName)
    PhysLib.callTable[3] = "(" .. self:CleanPath(PhysLib.callbackPath) .. ", "
    modName = modName or self.ModName
    self.ModName = modName
    local apiVersion = self:Call("RegisterMod", modName)
    
    if apiVersion == nil then
        Log("Error: PhysLibAPI: PhysLib not detected! Make sure you require the PhysLib mod in your mod.lua file")
    end
    if apiVersion == self.Version then
        return
    elseif apiVersion > self.Version then
        Log("Error: PhysLibAPI: The API interface in this mod (".. modName .. ") is outdated, please consider updating the mod with a new version of the API!")
        Log("Interface version " .. self.Version .. ", API version " .. apiVersion)
    else
        Log("Error: PhysLibAPI: The API interface in this mod (".. modName .. ") is too new for this version of the API!")
        Log("Interface version " .. self.Version .. ", API version " .. apiVersion)
    end
end


-- #endregion


-- #region event subscriber
function PhysLib:SubscribeToEvent(apiFunction, localFunction)
    return self:Call("SubscribeToEvent", self.callbackPath, apiFunction, localFunction)
end
-- #endregion
-- #region API

local defaultLinkDefinition = {DynamicFriction = 4,       StaticFriction = 8,         ConveyorSpeed = 0,        Conveyor = false}

local defaultObjectDefinition = {

    springConst = 3,
    dampening = 0.45,
    DynamicFriction = 4,
    StaticFriction = 4,
    CollidesWithOthers = false
}



--#region physics object
function PhysLib:RegisterPhysicsObject(pos, radius, velocity, objectDefinitionSaveName, effectPath)
    pos = pos or Vec3(0, 0, 0)
    radius = radius or (50 / 2)
    velocity = velocity or Vec3(0, 0, 0)
    objectDefinitionSaveName = objectDefinitionSaveName or ""

    --self:Parse("RegisterPhysicsObject", pos, radius, velocity, objectDefinitionSaveName, effectPath)
    return self:Call("RegisterPhysicsObject", pos, radius, velocity, objectDefinitionSaveName, effectPath)
    --return self.RV
end

function PhysLib:UnregisterPhysicsObject(objectId)
    return self:Call("UnregisterPhysicsObject", objectId)
end

function PhysLib:GetObject(objectId)
    return self:Call("GetObject", objectId)
end

function PhysLib:GetObjectPosition(objectId)
    return self:Call("GetObjectPosition", objectId)
end

function PhysLib:SetObjectPosition(objectId, pos)
    pos = self:StringifyTable(pos)
    return self:Call("SetObjectPosition", objectId, pos)
end

function PhysLib:GetObjectVelocity(objectId)
    return self:Call("GetObjectVelocity", objectId)
end

function PhysLib:SetObjectVelocity(objectId, velocity)
    velocity = self:StringifyTable(velocity)
    return self:Call("SetObjectVelocity", objectId, velocity)
end

function PhysLib:GetObjectRadius(objectId)
    return self:Call("GetObjectRadius", objectId)
end

function PhysLib:SetObjectRadius(objectId, radius)
    return self:Call("SetObjectRadius", objectId, radius)
end

function PhysLib:GetObjectsObjectDefinitionSaveName(objectId)
    return self:Call("GetObjectDefinitionSaveName", objectId)
end
function PhysLib:GetObjectsObjectDefinition(objectId)
    return self:Call("GetObjectDefinition", objectId)
end

function PhysLib:SetObjectsObjectDefinition(objectId, objectDefinitionSaveName)
    return self:Call("SetObjectDefinition", objectId, objectDefinitionSaveName)
end

function PhysLib:TerrainCircleCollision(posx, posy, radius)
    return self:Call("TerrainCircleCollision", posx, posy, radius)
end

function PhysLib:StructureRayCast(posA, posB)
    return self:Call("StructureRayCast", posA, posB)
end
--#endregion
--#region physics object definition

function PhysLib:RegisterObjectDefinition(objectDefinitionSaveName, objectDefinition)
    if not objectDefinitionSaveName or objectDefinitionSaveName == "" then
        return
    end
    objectDefinition = objectDefinition or defaultObjectDefinition
    return self:Call("RegisterObjectDefinition", objectDefinitionSaveName, objectDefinition)
end

function PhysLib:GetObjectDefinition(objectDefinitionSaveName)
    if objectDefinitionSaveName == nil or objectDefinitionSaveName == "" then
        return
    end
    return self:Call("GetObjectDefinition", objectDefinitionSaveName)
end

function PhysLib:UnregisterObjectDefinition(objectDefinitionSaveName)
    if objectDefinitionSaveName == nil or objectDefinitionSaveName == "" then
        return
    end
    return self:Call("UnregisterObjectDefinition", objectDefinitionSaveName)
end
--#endregion
--#region link definition
function PhysLib:RegisterLinkDefinition(linkDefinitionSaveName, linkDefinition)
    if not linkDefinitionSaveName or linkDefinitionSaveName == "" then
        return
    end
    linkDefinition = linkDefinition or defaultLinkDefinition
end
function PhysLib:GetLinkDefinition(linkDefinitionSaveName)
    if linkDefinitionSaveName == nil or linkDefinitionSaveName == "" then
        return
    end
    return self:Call("GetLinkDefinition", linkDefinitionSaveName)
end

function PhysLib:UnregisterLinkDefinition(linkDefinitionSaveName)
    if linkDefinitionSaveName == nil or linkDefinitionSaveName == "" then
        return
    end
    return self:Call("UnregisterLinkDefinition", linkDefinitionSaveName)
end
--#endregion

-- #endregion