-- This is the main API interface, do not edit this file!
function ExtractSteamId(str)
    str = str:gsub("\\", "/")
    return str:match("([^/]+)$")
end

PhysLib = {
    --Path = "mods/physlib/script.lua",
    Path = "mods/3386439236",
    callbackPath = "'mods/" .. ExtractSteamId(path) .. "/script.lua'",
    Version = 1.2,


    -- concats to "apiFunction(thisScriptPath, additionalArg, additionalArg)"
    callTable = {"PhysLib.API:", "apiFunction", "(thisScriptPath, ", "additionalArg, additionalArg,", ")"},
    

    ModName = "Undefined mod name, please parse in PhysLib:Load()",
}
-- #region wrapper





local path = PhysLib.Path
local callTable = PhysLib.callTable 
function PhysLib:Parse(APIFunc, ...)
    callTable[2] = APIFunc
    callTable[4] = table.concat({...}, ", ")
    local scriptCall = table.concat(callTable)
    ExecuteInScript(path, -1, scriptCall)
end


function PhysLib:MakeNestedString(str)
    return "'" .. str .. "'"
end

function PhysLib:StringifyTable(t)
    if type(t) == "table" then
        local str = "{"
        for k, v in pairs(t) do
            str = str .. k .. "=" .. self:StringifyTable(v) .. ","
        end
        str = str .. "}"
        return str
    elseif type(t) == "string" then
        return self:MakeNestedString(t)
    else
        return tostring(t)
    end

end

function PhysLib:MakeBackSlashesForwardSlashes(str)
    return string.gsub(str, "\\", "/")
end

function PhysLib:CleanPath(path)
    return string.gsub(path, "\\", "\\\\")
end

function PhysLib:Load(modName)
    PhysLib.callTable[3] = "(" .. self:CleanPath(PhysLib.callbackPath) .. ", "
    modName = modName or self.ModName
    self.ModName = modName
    self:Parse("ValidateVersion", self:MakeNestedString(modName))
    local apiVersion = self.RV
    if apiVersion == nil then
        Log("Error: PhysLibAPI: PhysLib not detected! Make sure you require the PhysLib mod in your mod.lua file")
    end
    if apiVersion == self.Version then
        return
    elseif apiVersion > self.Version then
        Log("Error: PhysLibAPI: The API interface in this mod (".. modName .. ") is outdated, please consider updating the mod with a new version of the API!")
        Log("Interface version " .. self.Version .. ", API version " .. apiVersion)
    else
        Log("Error: PhysLibAPI: The API interface in this mod (".. modName .. ") is too new for this version of the API!")
        Log("Interface version " .. self.Version .. ", API version " .. apiVersion)
    end
end


-- #endregion


-- #region event subscriber
function PhysLib:SubscribeToEvent(apiFunction, localFunction)
    apiFunction = self:MakeNestedString(apiFunction)
    localFunction = self:MakeNestedString(localFunction)
    self:Parse("SubscribeToEvent", apiFunction, localFunction)
end
-- #endregion
-- #region API

local defaultLinkDefinition = {DynamicFriction = 4,       StaticFriction = 8,         ConveyorSpeed = 0,        Conveyor = false}

local defaultObjectDefinition = {

    springConst = 3,
    dampening = 0.45,
    DynamicFriction = 4,
    StaticFriction = 4,
    CollidesWithOthers = false
}



--#region physics object
function PhysLib:RegisterPhysicsObject(pos, radius, velocity, objectDefinitionSaveName, effectPath)
    pos = pos or Vec3(0, 0, 0)
    radius = radius or (50 / 2)
    velocity = velocity or Vec3(0, 0, 0)
    objectDefinitionSaveName = objectDefinitionSaveName or ""

    pos = self:StringifyTable(pos)
    velocity = self:StringifyTable(velocity)
    objectDefinitionSaveName = self:MakeNestedString(objectDefinitionSaveName)
    effectPath = self:MakeNestedString(self:MakeBackSlashesForwardSlashes(effectPath))
    self:Parse("RegisterPhysicsObject", pos, radius, velocity, objectDefinitionSaveName, effectPath)
    return self.RV
end

function PhysLib:UnregisterPhysicsObject(objectId)
    self:Parse("UnregisterPhysicsObject", objectId)
    return self.RV
end

function PhysLib:GetObject(objectId)
    self:Parse("GetObject", objectId)
    return self.RV
end

function PhysLib:GetObjectPosition(objectId)
    self:Parse("GetObjectPosition", objectId)
    return self.RV
end

function PhysLib:SetObjectPosition(objectId, pos)
    pos = self:StringifyTable(pos)
    self:Parse("SetObjectPosition", objectId, pos)
    return self.RV
end

function PhysLib:GetObjectVelocity(objectId)
    self:Parse("GetObjectVelocity", objectId)
    return self.RV
end

function PhysLib:SetObjectVelocity(objectId, velocity)
    velocity = self:StringifyTable(velocity)
    self:Parse("SetObjectVelocity", objectId, velocity)
    return self.RV
end

function PhysLib:GetObjectRadius(objectId)
    self:Parse("GetObjectRadius", objectId)
    return self.RV
end

function PhysLib:SetObjectRadius(objectId, radius)
    self:Parse("SetObjectRadius", objectId, radius)
    return self.RV
end

function PhysLib:GetObjectsObjectDefinitionSaveName(objectId)
    self:Parse("GetObjectDefinitionSaveName", objectId)
    return self.RV
end
function PhysLib:GetObjectsObjectDefinition(objectId)
    self:Parse("GetObjectDefinition", objectId)
    return self.RV
end

function PhysLib:SetObjectsObjectDefinition(objectId, objectDefinitionSaveName)
    objectDefinitionSaveName = self:MakeNestedString(objectDefinitionSaveName)
    self:Parse("SetObjectDefinition", objectId, objectDefinitionSaveName)
    return self.RV
end

function PhysLib:TerrainCircleCollision(posx, posy, radius)
    self:Parse("TerrainCircleCollision", posx, posy, radius)
    return self.RV
end

function PhysLib:StructureRayCast(posA, posB)
    posA = self:StringifyTable(posA)
    posB = self:StringifyTable(posB)
    self:Parse("StructureRayCast", posA, posB)
end
--#endregion
--#region physics object definition

function PhysLib:RegisterObjectDefinition(objectDefinitionSaveName, objectDefinition)
    if not objectDefinitionSaveName or objectDefinitionSaveName == "" then
        return
    end
    objectDefinition = objectDefinition or defaultObjectDefinition


    objectDefinitionSaveName = self:MakeNestedString(objectDefinitionSaveName)
    objectDefinition = self:StringifyTable(objectDefinition)
    self:Parse("RegisterObjectDefinition", objectDefinitionSaveName, objectDefinition)
    return self.RV
end

function PhysLib:GetObjectDefinition(objectDefinitionSaveName)
    if objectDefinitionSaveName == nil or objectDefinitionSaveName == "" then
        return
    end
    objectDefinitionSaveName = self:MakeNestedString(objectDefinitionSaveName)
    self:Parse("GetObjectDefinition", objectDefinitionSaveName)
    return self.RV
end

function PhysLib:UnregisterObjectDefinition(objectDefinitionSaveName)
    if objectDefinitionSaveName == nil or objectDefinitionSaveName == "" then
        return
    end
    objectDefinitionSaveName = self:MakeNestedString(objectDefinitionSaveName)
    self:Parse("UnregisterObjectDefinition", objectDefinitionSaveName)
    return self.RV
end
--#endregion
--#region link definition
function PhysLib:RegisterLinkDefinition(linkDefinitionSaveName, linkDefinition)
    if not linkDefinitionSaveName or linkDefinitionSaveName == "" then
        return
    end
    linkDefinition = linkDefinition or defaultLinkDefinition
end
function PhysLib:GetLinkDefinition(linkDefinitionSaveName)
    if linkDefinitionSaveName == nil or linkDefinitionSaveName == "" then
        return
    end
    linkDefinitionSaveName = self:MakeNestedString(linkDefinitionSaveName)
    self:Parse("GetLinkDefinition", linkDefinitionSaveName)
    return self.RV
end

function PhysLib:UnregisterLinkDefinition(linkDefinitionSaveName)
    if linkDefinitionSaveName == nil or linkDefinitionSaveName == "" then
        return
    end
    linkDefinitionSaveName = self:MakeNestedString(linkDefinitionSaveName)
    self:Parse("UnregisterLinkDefinition", linkDefinitionSaveName)
    return self.RV
end
--#endregion

-- #endregion